using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LabWork2.AcademicDisciplines;
using LabWork2.Education;
namespace LabWork2
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.OutputEncoding = Encoding.Unicode;
            Console.InputEncoding = Encoding.Unicode;
            Student student1 = new Student();
            Student student2 = new Student();
            Student student3 = new Student();
            Student student4 = new Student();
            Student student5 = new Student();
            Student student6 = new Student();
            Student student7 = new Student();
            Student student8 = new Student();
            Student student9 = new Student();
            Student student10 = new Student();
            Student student11 = new Student();
            Student student12 = new Student();
            Student student13 = new Student();
            Student student14 = new Student();
            Student student15 = new Student();
            Student student16 = new Student();
            Student student17 = new Student();
            Student student18 = new Student();
            Student student19 = new Student();
            Student student20 = new Student();
            Student student21 = new Student();
            Student student22 = new Student();
            Student student23 = new Student();
            Student student24 = new Student();
            student1.Name = "Сергійчук Сергій Сергійович";
            student1.Age = 17;
            student1.Course = 1;
            student1.Gender = "чоловіча";
            student1.IntellectLevel("хороший");
            student1.StudentID = "DD121345678";
            student2.Name = "Круглик Іван Сергійович";
            student2.Age = 17;
            student2.Course = 1;
            student2.Gender = "чоловіча";
            student2.IntellectLevel("хороший");
            student2.StudentID = "DD121345678";
            student3.Name = "Сергійчук Сергій Григорович";
            student3.Age = 17;
            student3.Course = 1;
            student3.Gender = "чоловіча";
            student3.IntellectLevel("хороший");
            student3.StudentID = "DD121345678";
            student4.Name = "Білотіл Олег Данилович";
            student4.Age = 17;
            student4.Course = 1;
            student4.Gender = "чоловіча";
            //student4.MathKnowledgeLevel.Level = 5;
            //student4.PhysicKnowledgeLevel.Level = 5;
            //student4.EnglishKnowledgeLevel.Level = 5;
            student4.IntellectLevel("хороший");
            student4.StudentID = "DD121345678";
            student5.Name = "Калиніч Абрам Тигранович";
            student5.Age = 17;
            student5.Course = 1;
            student5.Gender = "чоловіча";
            //student5.MathKnowledgeLevel.Level = 5;
            //student5.PhysicKnowledgeLevel.Level = 5;
            //student5.EnglishKnowledgeLevel.Level = 5;
            student5.IntellectLevel("хороший");
            student5.StudentID = "DD121345678";
            student6.Name = "Медведчук Антон Едуардович";
            student6.Age = 17;
            student6.Course = 1;
            student6.Gender = "чоловіча";
            //student6.MathKnowledgeLevel.Level = 5;
            //student6.PhysicKnowledgeLevel.Level = 5;
            //student6.EnglishKnowledgeLevel.Level = 5;
            student6.IntellectLevel("хороший");
            student6.StudentID = "DD121345678";
            student7.Name = "Смицький Роман Сергійович";
            student7.Age = 17;
            student7.Course = 1;
            student7.Gender = "чоловіча";
            //student7.MathKnowledgeLevel.Level = 5;
            //student7.PhysicKnowledgeLevel.Level = 5;
            //student7.EnglishKnowledgeLevel.Level = 5;
            student7.IntellectLevel("хороший");
            student7.StudentID = "DD121345678";
            student8.Name = "Бутко Василь Павлович";
            student8.Age = 17;
            student8.Course = 1;
            student8.Gender = "чоловіча";
            //student8.MathKnowledgeLevel.Level = 5;
            //student8.PhysicKnowledgeLevel.Level = 5;
            //.EnglishKnowledgeLevel.Level = 5;
            student8.IntellectLevel("хороший");
            student8.StudentID = "DD121345678";
            student9.Name = "Кузнець Дмитро Дмитрович";
            student9.Age = 17;
            student9.Course = 1;
            student9.Gender = "чоловіча";
            //student9.MathKnowledgeLevel.Level = 5;
            //student9.PhysicKnowledgeLevel.Level = 5;
            //student9.EnglishKnowledgeLevel.Level = 5;
            student9.IntellectLevel("хороший");
            student9.StudentID = "DD121345678";
            student10.Name = "Опанасенко Михайло Федорович";
            student10.Age = 17;
            student10.Course = 1;
            student10.Gender = "чоловіча";
            //student10.MathKnowledgeLevel.Level = 5;
            //student10.PhysicKnowledgeLevel.Level = 5;
            //student10.EnglishKnowledgeLevel.Level = 5;
            student10.IntellectLevel("хороший");
            student10.StudentID = "DD121345678";
            student11.Name = "Патау Давид Пантелеймонович";
            student11.Age = 17;
            student11.Course = 1;
            student11.Gender = "чоловіча";
            //student11.MathKnowledgeLevel.Level = 5;
            //student11.PhysicKnowledgeLevel.Level = 5;
            //student11.EnglishKnowledgeLevel.Level = 5;
            student11.IntellectLevel("хороший");
            student11.StudentID = "DD121345678";
            student12.Name = "Задорожний Дмитро Олександрович";
            student12.Age = 17;
            student12.Course = 1;
            student12.Gender = "чоловіча";
            //student12.MathKnowledgeLevel.Level = 5;
            //student12.PhysicKnowledgeLevel.Level = 5;
            //student12.EnglishKnowledgeLevel.Level = 5;
            student12.IntellectLevel("хороший");
            student12.StudentID = "DD121345678";
            student13.Name = "Радчук Олександр Ярославович";
            student13.Age = 17;
            student13.Course = 1;
            student13.Gender = "чоловіча";
            //student13.MathKnowledgeLevel.Level = 5;
            //student13.PhysicKnowledgeLevel.Level = 5;
            //student13.EnglishKnowledgeLevel.Level = 5;
            student13.IntellectLevel("хороший");
            student13.StudentID = "DD121345678";
            student14.Name = "Кий Руслан Григорович";
            student14.Age = 17;
            student14.Course = 1;
            student14.Gender = "чоловіча";
            //student14.MathKnowledgeLevel.Level = 5;
            //student14.PhysicKnowledgeLevel.Level = 5;
            //student14.EnglishKnowledgeLevel.Level = 5;
            student14.IntellectLevel("хороший");
            student14.StudentID = "DD121345678";
            student15.Name = "Галицький Данило Романович";
            student15.Age = 17;
            student15.Course = 1;
            student15.Gender = "чоловіча";
            // student15.MathKnowledgeLevel.Level = 5;
            //student15.PhysicKnowledgeLevel.Level = 5;
            //student15.EnglishKnowledgeLevel.Level = 5;
            student15.IntellectLevel("хороший");
            student15.StudentID = "DD121345678";
            student16.Name = "Павленко Сергій Сергійович";
            student16.Age = 17;
            student16.Course = 1;
            student16.Gender = "чоловіча";
            //student16.MathKnowledgeLevel.Level = 5;
            //student16.PhysicKnowledgeLevel.Level = 5;
            //student16.EnglishKnowledgeLevel.Level = 5;
            student16.IntellectLevel("хороший");
            student16.StudentID = "DD121345678";
            student17.Name = "Абрамович Федір Борисович";
            student17.Age = 17;
            student17.Course = 1;
            student17.Gender = "чоловіча";
            //student17.MathKnowledgeLevel.Level = 5;
            //student17.PhysicKnowledgeLevel.Level = 5;
            //student17.EnglishKnowledgeLevel.Level = 5;
            student17.IntellectLevel("хороший");
            student17.StudentID = "DD121345678";
            student18.Name = "Гадза Оксана Валентинівна";
            student18.Age = 17;
            student18.Course = 1;
            student18.Gender = "жіноча";
            //student18.MathKnowledgeLevel.Level = 5;
            //student18.PhysicKnowledgeLevel.Level = 5;
            //student18.EnglishKnowledgeLevel.Level = 5;
            student18.IntellectLevel("хороший");
            student18.StudentID = "DD121345678";
            student19.Name = "Герасимчук Ірина Богданівна";
            student19.Age = 16;
            student19.Course = 1;
            student19.Gender = "жіноча";
            //student19.MathKnowledgeLevel.Level = 5;
            //student19.PhysicKnowledgeLevel.Level = 5;
            //student19.EnglishKnowledgeLevel.Level = 5;
            student19.IntellectLevel("хороший");
            student19.StudentID = "DD121345678";
            student20.Name = "Франко Тарас Гнатович";
            student20.Age = 18;
            student20.Course = 1;
            student20.Gender = "чоловіча";
            //student20.MathKnowledgeLevel.Level = 5;
            //student20.PhysicKnowledgeLevel.Level = 5;
            //student20.EnglishKnowledgeLevel.Level = 5;
            student20.IntellectLevel("хороший");
            student20.StudentID = "DD121345678";
            student21.Name = "Приходько Марія Богданівна";
            student21.Age = 17;
            student21.Course = 1;
            student21.Gender = "жіноча";
            //student21.MathKnowledgeLevel.Level = 5;
            //student21.PhysicKnowledgeLevel.Level = 5;
            //student21.EnglishKnowledgeLevel.Level = 5;
            student21.IntellectLevel("хороший");
            student21.StudentID = "DD121345678";
            student22.Name = "Бульба Ростислав Іванович";
            student22.Age = 17;
            student22.Course = 1;
            student22.Gender = "чоловіча";
            //student22.MathKnowledgeLevel.Level = 5;
            //student22.PhysicKnowledgeLevel.Level = 5;
            //student22.EnglishKnowledgeLevel.Level = 5;
            student22.IntellectLevel("хороший");
            student22.StudentID = "DD121345678";
            student23.Name = "Гурченко Світлана Борисівна";
            student23.Age = 17;
            student23.Course = 1;
            student23.Gender = "жіноча";
            //student23.MathKnowledgeLevel.Level = 5;
            //student23.PhysicKnowledgeLevel.Level = 5;
            //student23.EnglishKnowledgeLevel.Level = 5;
            student23.IntellectLevel("хороший");
            student23.StudentID = "DD121345678";
            student24.Name = "Коваль Владислав Миколайович";
            student24.Age = 17;
            student24.Course = 1;
            student24.Gender = "чоловіча";
            //student24.MathKnowledgeLevel.Level = 5;
            //student24.PhysicKnowledgeLevel.Level = 5;
            //student24.EnglishKnowledgeLevel.Level = 5;
            student24.IntellectLevel("хороший");
            student24.StudentID = "DD121345678";
            List<Student> list = new List<Student>();
            list.Add(student1);
            list.Add(student2);
            list.Add(student3);
            list.Add(student4);
            list.Add(student5);
            list.Add(student6);
            list.Add(student7);
            list.Add(student8);
            list.Add(student9);
            list.Add(student10);
            list.Add(student11);
            list.Add(student12);
            list.Add(student13);
            list.Add(student14);
            list.Add(student15);
            list.Add(student16);
            list.Add(student17);
            list.Add(student18);
            list.Add(student19);
            list.Add(student20);
            list.Add(student21);
            list.Add(student22);
            list.Add(student23);
            list.Add(student24);
            Group group = new Group(list);
            group.Name = "ПІ-101";
            ConMenu conMenu = new ConMenu();
            conMenu.StartMenu();
            Console.WriteLine("=========================================================");
            conMenu.WriteStudentsBeforeGroups(list);
            Console.WriteLine("=========================================================");
            conMenu.WriteStudentsAfterGroups(group.GetAllStudents);
            List<int> vs = new List<int>();           
        }
    }
}
